# Generated by Django 3.2.5 on 2021-07-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Car Make', max_length=25)),
                ('description', models.CharField(default='Description of car make or manufacturer.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dealership', models.IntegerField(default=0)),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('wagon', 'Station Wagon'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('vans', 'Van / Minivan'), ('sports', 'Sports Car'), ('muscle', 'Muscle Car'), ('super', 'Super Car'), ('electric', 'Electric Car'), ('limo', 'Limousine')], default='coupe', max_length=15)),
                ('car_year', models.DateField()),
                ('car_make', models.ManyToManyField(to='djangoapp.CarMake')),
            ],
        ),
    ]
