# Generated by Django 3.2.5 on 2021-07-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmake',
            name='id',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='carmake',
            name='mkid',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='mdid',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_make',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.carmake'),
        ),
    ]
